'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {createContext,useContext,useState,useEffect} from 'react';
import {ArrowUpRight, Menu, X} from 'lucide-react';
import type {Period} from '@/lib/model';
const Context=createContext<{period:Period;setPeriod:(p:Period)=>void}>({period:'all',setPeriod:()=>{}});
export const usePeriod=()=>useContext(Context);
export function PeriodToggle(){const {period,setPeriod}=usePeriod();return <div className="period" role="group" aria-label="Review period"><button aria-pressed={period==='all'} onClick={()=>setPeriod('all')}>All time</button><button aria-pressed={period==='recent'} onClick={()=>setPeriod('recent')}>2022–2026</button></div>}
export function Shell({children}:{children:React.ReactNode}){const [period,setPeriod]=useState<Period>('all');const [menu,setMenu]=useState(false);const pathname=usePathname();useEffect(()=>{const saved=sessionStorage.getItem('rmr-period');if(saved==='recent')setPeriod(saved)},[]);const choose=(p:Period)=>{setPeriod(p);sessionStorage.setItem('rmr-period',p)};const links=[['Home','/'],['Professors','/professors/'],['Departments / Schools','/departments/'],['Other Fun Statistics','/statistics/'],['About','/about/']];return <Context.Provider value={{period,setPeriod:choose}}><header className="site-header"><Link href="/" className="wordmark">rate my<br/><span>richmond<span className="brand-dot">.</span></span></Link><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''} aria-label="Main navigation">{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setMenu(false)} aria-current={(href==='/'?pathname==='/':pathname.startsWith(href))?'page':undefined}>{label}</Link>)}</nav><span className="header-note">An unofficial student project <ArrowUpRight size={14}/></span></header><main id="main">{children}</main><footer><Link href="/" className="footer-brand">Rate My Richmond.</Link><span>Anonymous opinions. Actual numbers.</span><Link href="/about/">Built by Gleb <ArrowUpRight size={14}/></Link></footer></Context.Provider>}
