'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {createContext,useContext,useState,useEffect,useCallback} from 'react';
import {ArrowUpRight, Menu, X} from 'lucide-react';
import {ComparisonProvider,ComparisonTray} from './comparison-context';
import type {Period} from '@/lib/model';
const Context=createContext<{period:Period;setPeriod:(p:Period)=>void}>({period:'all',setPeriod:()=>{}});
export const usePeriod=()=>useContext(Context);
export function PeriodToggle(){const {period,setPeriod}=usePeriod();return <div className="period" role="group" aria-label="Review period"><button aria-pressed={period==='all'} onClick={()=>setPeriod('all')}>All time</button><button aria-pressed={period==='recent'} onClick={()=>setPeriod('recent')}>2022–2026</button></div>}
export function Shell({children}:{children:React.ReactNode}){const [period,updatePeriod]=useState<Period>('all');const setPeriod=useCallback((p:Period)=>{updatePeriod(p);try{sessionStorage.setItem('rmr-period',p)}catch{}},[]);const [menu,setMenu]=useState(false);const pathname=usePathname();useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('period');if(requested==='all'||requested==='recent'){setPeriod(requested);return}try{const saved=sessionStorage.getItem('rmr-period');if(saved==='recent')setPeriod(saved)}catch{}},[setPeriod]);const choose=setPeriod;const links=[['Home','/'],['Professors','/professors/'],['Compare','/compare/'],['Departments','/departments/'],['Statistics','/statistics/'],['About','/about/']];return <Context.Provider value={{period,setPeriod:choose}}><ComparisonProvider><header className="site-header"><Link href="/" className="wordmark">rate my<br/><span>richmond<span className="brand-dot">.</span></span></Link><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''} aria-label="Main navigation">{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setMenu(false)} aria-current={(href==='/'?pathname==='/':pathname.startsWith(href))?'page':undefined}>{label}</Link>)}</nav><span className="header-note">Independent student project <ArrowUpRight size={14}/></span></header><main id="main">{children}</main><footer><Link href="/" className="footer-brand">Rate My Richmond.</Link><span>Student reviews, with context.</span><Link href="/about/">About & methodology <ArrowUpRight size={14}/></Link></footer><ComparisonTray/></ComparisonProvider></Context.Provider>}
